{"version": 2, "width": 0, "height": 0, "timestamp": 1694455644, "env": {"SHELL": null, "TERM": null}, "title": "NATS by Example: jetstream/limits-stream/python"}
[2.438085, "o", "\u001b[1A\u001b[1B\u001b[0G\u001b[?25l[+] Creating 2/0\r\n"]
[2.439216, "o", " \u001b[32m✔\u001b[0m Network 263e8d57_default   \u001b[32mCreated\u001b[0m\u001b[34m0.1s \u001b[0m\r\n \u001b[32m✔\u001b[0m Container 263e8d57-nats-1  \u001b[32mCreated\u001b[0m\u001b[34m0.0s \u001b[0m\r\n\u001b[?25h"]
[2.539248, "o", "\u001b[1A\u001b[1B\u001b[0G"]
[2.539336, "o", "\u001b[?25l"]
[2.539377, "o", "[+] Running 0/0"]
[2.539409, "o", "\r\n"]
[2.539618, "o", "\r\n"]
[2.539659, "o", "\u001b[?25h"]
[2.733333, "o", "\u001b[1A\u001b[1A\u001b[0G\u001b[?25l\u001b[34m[+] Running 1/1\u001b[0m\r\n \u001b[32m✔\u001b[0m Container 263e8d57-nats-1  \u001b[32mStarted\u001b[0m\u001b[34m0.3s \u001b[0m\r\n\u001b[?25h"]
[3.09626, "o", "Traceback (most recent call last):"]
[3.0964, "o", "\r\n"]
[3.096432, "o", "  File \"//main.py\", line 74, in <module>"]
[3.096455, "o", "\r\n"]
[3.09707, "o", "    asyncio.run(main())"]
[3.097112, "o", "\r\n"]
[3.097135, "o", "  File \"/usr/local/lib/python3.10/asyncio/runners.py\", line 44, in run"]
[3.09716, "o", "\r\n"]
[3.097182, "o", "    return loop.run_until_complete(main)"]
[3.097204, "o", "\r\n"]
[3.097224, "o", "  File \"/usr/local/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"]
[3.09725, "o", "\r\n"]
[3.103101, "o", "    return future.result()"]
[3.103189, "o", "\r\n  File \"//main.py\", line 22, in main\r\n    await js.delete_stream('events')\r\n  File \"/usr/local/lib/python3.10/site-packages/nats/js/manager.py\", line 120, in delete_stream\r\n    resp = await self._api_request(\r\n  File \"/usr/local/lib/python3.10/site-packages/nats/js/manager.py\", line 362, in _api_request\r\n    raise APIError.from_error(resp['error'])\r\n  File \"/usr/local/lib/python3.10/site-packages/nats/js/errors.py\", line 84, in from_error\r\n    raise NotFoundError(**err)\r\nnats.js.errors.NotFoundError: nats: NotFoundError: code=404 err_code=10059 description='stream not found'\r\n"]
[3.655954, "o", "exit status 1\r\n"]
